server:
  port: ${PORT:8080}

spring:
  application:
    name: skillGapAnalyzer
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true
  main:
    allow-circular-references: true

jwt:
    secret: ${JWT_SECRET}
    expiration: 3600000

github:
  url: https://api.github.com/search/repositories?q=
  token: ${GITHUB_TOKEN}
